// <auto-generated />
namespace Telerik.ILS.Common
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Security.Cryptography;
    using System.Text;
    using System.Text.RegularExpressions;

    /// <summary>
    /// Extension class for String class containing methods for manipulating strings.
    /// </summary>
    public static class StringExtensions
    {
        /// <summary>
        /// Converts input string to hexadecimal.
        /// </summary>
        /// <param name="input">Input string parameter.</param>
        /// <returns>Return the input string as hexadecimal string.</returns>
        public static string ToMd5Hash(this string input)
        {
            var md5Hash = MD5.Create();

            // Convert the input string to a byte array and compute the hash.
            var data = md5Hash.ComputeHash(Encoding.UTF8.GetBytes(input));

            // Create a new StringBuilder to collect the bytes
            // and create a string.
            var builder = new StringBuilder();

            // Loop through each byte of the hashed data 
            // and format each one as a hexadecimal string.
            for (int i = 0; i < data.Length; i++)
            {
                builder.Append(data[i].ToString("x2"));
            }

            // Return the hexadecimal string.
            return builder.ToString();
        }

        /// <summary>
        /// Check if the input string is contained in given array.
        /// </summary>
        /// <param name="input">Input string parameter.</param>
        /// <returns>Return boolean type value.</returns>
        public static bool ToBoolean(this string input)
        {
            var stringTrueValues = new[] { "true", "ok", "yes", "1", "да" };
            return stringTrueValues.Contains(input.ToLower());
        }

        /// <summary>
        /// Parse the input string to short type value.
        /// </summary>
        /// <param name="input">Input string parameter.</param>
        /// <returns>Returns short type value.</returns>
        public static short ToShort(this string input)
        {
            short shortValue;
            short.TryParse(input, out shortValue);
            return shortValue;
        }

        /// <summary>
        /// Parse the input string to integer type value.
        /// </summary>
        /// <param name="input">Input string parameter.</param>
        /// <returns>Returns integer type value.</returns>
        public static int ToInteger(this string input)
        {
            int integerValue;
            int.TryParse(input, out integerValue);
            return integerValue;
        }

        /// <summary>
        /// Parse the input string to long type value.
        /// </summary>
        /// <param name="input">Input string parameter.</param>
        /// <returns>Returns long type value.</returns>
        public static long ToLong(this string input)
        {
            long longValue;
            long.TryParse(input, out longValue);
            return longValue;
        }

        /// <summary>
        /// Parse the input string to DateTime type value.
        /// </summary>
        /// <param name="input">Input string parameter.</param>
        /// <returns>Returns DateTime type value.</returns>
        public static DateTime ToDateTime(this string input)
        {
            DateTime dateTimeValue;
            DateTime.TryParse(input, out dateTimeValue);
            return dateTimeValue;
        }

        /// <summary>
        /// Capitalize the first letter of the input string.
        /// </summary>
        /// <param name="input">Input string parameter.</param>
        /// <returns>
        /// If the input string is not null or empty, returns the input string with capitalized first letter.
        /// If the input string is null or empty, returns the original input string.
        /// </returns>
        public static string CapitalizeFirstLetter(this string input)
        {
            if (string.IsNullOrEmpty(input))
            {
                return input;
            }

            return input.Substring(0, 1).ToUpper(CultureInfo.CurrentCulture) + input.Substring(1, input.Length - 1);
        }

        /// <summary>
        /// Gets the substring between given start and end string from the input string.
        /// </summary>
        /// <param name="input">Input string parameter.</param>
        /// <param name="startString">Start string parameter.</param>
        /// <param name="endString">End string parameter.</param>
        /// <param name="startFrom">The start index where the search begins from</param>
        /// <returns>Returns the desired string between the start and end string parameter.</returns>
        public static string GetStringBetween(this string input, string startString, string endString, int startFrom = 0)
        {
            input = input.Substring(startFrom);
            startFrom = 0;
            if (!input.Contains(startString) || !input.Contains(endString))
            {
                return string.Empty;
            }

            // Returns the index of the char where the result should start
            var startPosition = input.IndexOf(startString, startFrom, StringComparison.Ordinal) + startString.Length;
            if (startPosition == -1)
            {
                return string.Empty;
            }

            // Returns the index of the char where the result should end
            var endPosition = input.IndexOf(endString, startPosition, StringComparison.Ordinal);
            if (endPosition == -1)
            {
                return string.Empty;
            }

            return input.Substring(startPosition, endPosition - startPosition);
        }

        /// <summary>
        /// Convert the cyrillic letters in the given input string to latin letters. 
        /// </summary>
        /// <param name="input">Input string parameter.</param>
        /// <returns>Returns the input string where the cyrillic letters are replaced with latin letters.</returns>
        public static string ConvertCyrillicToLatinLetters(this string input)
        {
            var bulgarianLetters = new[]
                                       {
                                           "а", "б", "в", "г", "д", "е", "ж", "з", "и", "й", "к", "л", "м", "н", "о", "п",
                                           "р", "с", "т", "у", "ф", "х", "ц", "ч", "ш", "щ", "ъ", "ь", "ю", "я"
                                       };
            var latinRepresentationsOfBulgarianLetters = new[]
                                                             {
                                                                 "a", "b", "v", "g", "d", "e", "j", "z", "i", "y", "k",
                                                                 "l", "m", "n", "o", "p", "r", "s", "t", "u", "f", "h",
                                                                 "c", "ch", "sh", "sht", "u", "i", "yu", "ya"
                                                             };

            // Loops through the characters and replaces cyrillic with latin letters
            for (var i = 0; i < bulgarianLetters.Length; i++)
            {
                input = input.Replace(bulgarianLetters[i], latinRepresentationsOfBulgarianLetters[i]);
                input = input.Replace(bulgarianLetters[i].ToUpper(), latinRepresentationsOfBulgarianLetters[i].CapitalizeFirstLetter());
            }

            return input;
        }

        /// <summary>
        /// Convert the latin letters in the given input string to cyrillic letters. 
        /// </summary>
        /// <param name="input">Input string parameter.</param>
        /// <returns>Returns the input string where the latin letters are replaced with cyrillic letters.</returns>
        public static string ConvertLatinToCyrillicKeyboard(this string input)
        {
            var latinLetters = new[]
                                   {
                                       "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p",
                                       "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"
                                   };

            var bulgarianRepresentationOfLatinKeyboard = new[]
                                                             {
                                                                 "а", "б", "ц", "д", "е", "ф", "г", "х", "и", "й", "к",
                                                                 "л", "м", "н", "о", "п", "я", "р", "с", "т", "у", "ж",
                                                                 "в", "ь", "ъ", "з"
                                                             };

            // Loops through the characters and replaces latin with cyrillic letters
            for (int i = 0; i < latinLetters.Length; i++)
            {
                input = input.Replace(latinLetters[i], bulgarianRepresentationOfLatinKeyboard[i]);
                input = input.Replace(latinLetters[i].ToUpper(), bulgarianRepresentationOfLatinKeyboard[i].ToUpper());
            }

            return input;
        }

        /// <summary>
        /// Convert the input string to valid username string.
        /// Replaces all the cyrillic letters with the corresponding latin ones.
        /// Removes all the numbers and invalid symbols.
        /// </summary>
        /// <param name="input">Input string parameter.</param>
        /// <returns>Returns valid username as string.</returns>
        public static string ToValidUsername(this string input)
        {
            input = input.ConvertCyrillicToLatinLetters();

            // Removes all whitespace and unsupported in username symbols
            return Regex.Replace(input, @"[^a-zA-z0-9_\.]+", string.Empty);
        }

        /// <summary>
        /// Convert the input string to valid filename string.
        /// Replaces the cyrillic letters with the corresponding latin ones.
        /// </summary>
        /// <param name="input">Input string parameter.</param>
        /// <returns>Returns valid filename as string.</returns>
        public static string ToValidLatinFileName(this string input)
        {
            input = input.Replace(" ", "-").ConvertCyrillicToLatinLetters();

            // Removes all whitespace and unsupported in file name symbols ( dash is excluded )
            return Regex.Replace(input, @"[^a-zA-z0-9_\.\-]+", string.Empty);
        }

        /// <summary>
        /// Substrings the input string from the start with desire count of chars.
        /// </summary>
        /// <param name="input">Input string parameter.</param>
        /// <param name="charsCount">Count of the chars to be substring.</param>
        /// <returns>Returns the substring string formed with the desired count of chars.</returns>
        public static string GetFirstCharacters(this string input, int charsCount)
        {
            return input.Substring(0, Math.Min(input.Length, charsCount));
        }

        /// <summary>
        /// Gets the file extension from a string.
        /// </summary>
        /// <param name="fileName">Input string parameter.</param>
        /// <returns>
        /// If the input string is not null or empty, returns the file extension as string.
        /// If the input string is null or empty, returns empty string.
        /// If the input string does not contain file extension, returns empty string.
        /// </returns>
        public static string GetFileExtension(this string fileName)
        {
            if (string.IsNullOrWhiteSpace(fileName))
            {
                return string.Empty;
            }

            string[] fileParts = fileName.Split(new[] { "." }, StringSplitOptions.None);
            if (fileParts.Count() == 1 || string.IsNullOrEmpty(fileParts.Last()))
            {
                return string.Empty;
            }

            return fileParts.Last().Trim().ToLower();
        }

        /// <summary>
        /// Converts file extension string to file content type
        /// </summary>
        /// <param name="fileExtension">The input string</param>
        /// <returns>Returns the content type from the file extension</returns>
        public static string ToContentType(this string fileExtension)
        {
            var fileExtensionToContentType = new Dictionary<string, string>
                                                 {
                                                     { "jpg", "image/jpeg" },
                                                     { "jpeg", "image/jpeg" },
                                                     { "png", "image/x-png" },
                                                     {
                                                         "docx",
                                                         "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                                                     },
                                                     { "doc", "application/msword" },
                                                     { "pdf", "application/pdf" },
                                                     { "txt", "text/plain" },
                                                     { "rtf", "application/rtf" }
                                                 };
            if (fileExtensionToContentType.ContainsKey(fileExtension.Trim()))
            {
                return fileExtensionToContentType[fileExtension.Trim()];
            }

            // Returns default string content type if file extension is not contained in Dictionary
            return "application/octet-stream";
        }

        /// <summary>
        /// Convert the input string into byte array.
        /// </summary>
        /// <param name="input">Input string parameter.</param>
        /// <returns>Returns the input string as byte array.</returns>
        public static byte[] ToByteArray(this string input)
        {
            var bytesArray = new byte[input.Length * sizeof(char)];

            // Creates a copy of input array into bytesArray
            Buffer.BlockCopy(input.ToCharArray(), 0, bytesArray, 0, bytesArray.Length);
            return bytesArray;
        }
    }
}
